services:
  toposcale:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: toposcale-rila-pirin
    container_name: toposcale-rila-pirin
    volumes:
      - ./inputs:/app/inputs
      - ./outputs:/app/outputs
      - ./config:/app/config
      - ~/.cdsapirc:/root/.cdsapirc:ro
      - ./docker/state/bash_history:/root/.bash_history_persist
    tty: true
    stdin_open: true
    command: sleep infinity